# Generated by Django 5.2.4 on 2025-08-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_block_user', 'Может блокировать пользователей')]},
        ),
    ]
