# Generated by Django 5.2.4 on 2025-08-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_owner_message_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_disable_mailing', 'Может отключать рассылки')]},
        ),
    ]
